---
- name: Warming up cwl instance
  gather_facts: no
  hosts: instance_public_ip
  tasks:
  - name: Initial connection block
    block:
      - name: Wait 30 seconds, but only start checking after 5 seconds
        wait_for_connection:
          delay: 5
          timeout: 30
    rescue:
      - name: Disabling prompt for restarting while installing packages
        raw: echo '* libraries/restart-without-asking boolean true' | sudo debconf-set-selections
      - name: Try to install python 2, when ansible is not able to connect
        raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
    become: yes

  - name: Install python packages
    apt: name={{ item }} state=present
    with_items:
      - virtualenv
      - python-dev
      - python-setuptools
      - python3-pip
      - python3-venv

  - name: Install pipenv
    pip:
      name: pipenv
      version: "2021.5.29"
      executable: pip3
    become: yes

  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes force_apt_get=yes
    with_items:
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
       - aptitude

  - name: Make sure the user key is authorized on the CWL instance
    authorized_key: user="{{lookup('env','ANSIBLE_REMOTE_USER')}}" key="{{lookup('env','ssh_key')}}" exclusive=no state=present

- name: Install roles as a root
  hosts: instance_public_ip
  vars:
      nfs_install: "{{ lookup('env','TF_VAR_nfs_install') }}"
  become: yes
  roles:
    - role: 'indigo-dc.nfs'
      nfs_mode: 'client'
      nfs_client_imports:
        - local: "{{ lookup('env','TF_VAR_local_folder') }}"
          remote: "{{ lookup('env','TF_VAR_remote_folder') }}"
          server_host: "{{lookup('env','TF_VAR_nfs_server_host')}}"
      when: nfs_install == 'yes'
    - docker

- name: Setup CWL instance as a remote user - "{{lookup('env','ANSIBLE_REMOTE_USER')}}"
  hosts: instance_public_ip
  vars:
      workflow_url: "{{ lookup('env','TF_VAR_workflow_url') }}"
  become: yes
  become_user : "{{lookup('env','ANSIBLE_REMOTE_USER')}}"
  roles:
    - cwl
    - toil
    - git-clone
    - docker-venv

