---
# Tasks to install and configure CWL-runner

# Install dependencies for CWL-runner

- name: Install dependencies for cwl
  apt:
    name: ['python-pip', 'python-dev', 'virtualenv']
    state: present

# Install cwlref-runner in venv

- name: install cwl in virtualenv "{{lookup('env','ANSIBLE_REMOTE_USER')}}" - HOME
  pip:
    name: cwlref-runner
    virtualenv: ~/cwl_bioexcel
    virtualenv_python: python2.7
  become: yes
  become_user : "{{lookup('env','ANSIBLE_REMOTE_USER')}}"
