---

- name: Upload pipenv files to install cwl
  ansible.builtin.copy:
    src: cwl_bioexcel
    dest: ~/
    owner: "{{lookup('env','ANSIBLE_REMOTE_USER')}}"
    group: "{{lookup('env','ANSIBLE_REMOTE_USER')}}"
    mode: '0644'

# Install cwlref-runner in venv
- name: Install cwl and toil
  ansible.builtin.shell:
    cmd: pipenv install
    chdir: ~/cwl_bioexcel

# Activate virtual env while login
- name: Add line to bash_profile to activate virtual environment
  lineinfile:
    path: ~/.profile
    state: present
    line: 'cd ~/cwl_bioexcel && pipenv shell'
