---
# Install cwlref-runner in venv
- name: install cwl in virtualenv "{{lookup('env','ANSIBLE_REMOTE_USER')}}" - HOME
  pip:
    name: cwlref-runner
    virtualenv: ~/cwl_bioexcel
    virtualenv_python: python3

# Activate virtual env while login
- name: Add line to bash_profile to activate virtual environment
  lineinfile:
    path: ~/.profile
    state: present
    line: 'source ~/cwl_bioexcel/bin/activate'